// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Games/Cards.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XddCards.Grpc.Games {

  /// <summary>Holder for reflection information generated from Protos/Games/Cards.proto</summary>
  public static partial class CardsReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Games/Cards.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CardsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhQcm90b3MvR2FtZXMvQ2FyZHMucHJvdG8SBUNhcmRzIqMCCgtDYXJkTWVz",
            "c2FnZRImCgRzdWl0GAEgASgOMhguQ2FyZHMuQ2FyZE1lc3NhZ2UuU3VpdHMS",
            "JgoEcmFuaxgCIAEoDjIYLkNhcmRzLkNhcmRNZXNzYWdlLlJhbmtzIjgKBVN1",
            "aXRzEgkKBUNsdWJzEAASDAoIRGlhbW9uZHMQARIKCgZIZWFydHMQAhIKCgZT",
            "cGFkZXMQAyKJAQoFUmFua3MSBwoDQWNlEAASBwoDVHdvEAESCQoFVGhyZWUQ",
            "AhIICgRGb3VyEAMSCAoERml2ZRAEEgcKA1NpeBAFEgkKBVNldmVuEAYSCQoF",
            "RWlnaHQQBxIICgROaW5lEAgSBwoDVGVuEAkSCAoESmFjaxAKEgkKBVF1ZWVu",
            "EAsSCAoES2luZxAMQhaqAhNYZGRDYXJkcy5HcnBjLkdhbWVzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::XddCards.Grpc.Games.CardMessage), global::XddCards.Grpc.Games.CardMessage.Parser, new[]{ "Suit", "Rank" }, null, new[]{ typeof(global::XddCards.Grpc.Games.CardMessage.Types.Suits), typeof(global::XddCards.Grpc.Games.CardMessage.Types.Ranks) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CardMessage : pb::IMessage<CardMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CardMessage> _parser = new pb::MessageParser<CardMessage>(() => new CardMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CardMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XddCards.Grpc.Games.CardsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardMessage(CardMessage other) : this() {
      suit_ = other.suit_;
      rank_ = other.rank_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardMessage Clone() {
      return new CardMessage(this);
    }

    /// <summary>Field number for the "suit" field.</summary>
    public const int SuitFieldNumber = 1;
    private global::XddCards.Grpc.Games.CardMessage.Types.Suits suit_ = global::XddCards.Grpc.Games.CardMessage.Types.Suits.Clubs;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::XddCards.Grpc.Games.CardMessage.Types.Suits Suit {
      get { return suit_; }
      set {
        suit_ = value;
      }
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 2;
    private global::XddCards.Grpc.Games.CardMessage.Types.Ranks rank_ = global::XddCards.Grpc.Games.CardMessage.Types.Ranks.Ace;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::XddCards.Grpc.Games.CardMessage.Types.Ranks Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CardMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CardMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Suit != other.Suit) return false;
      if (Rank != other.Rank) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Suit != global::XddCards.Grpc.Games.CardMessage.Types.Suits.Clubs) hash ^= Suit.GetHashCode();
      if (Rank != global::XddCards.Grpc.Games.CardMessage.Types.Ranks.Ace) hash ^= Rank.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Suit != global::XddCards.Grpc.Games.CardMessage.Types.Suits.Clubs) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Suit);
      }
      if (Rank != global::XddCards.Grpc.Games.CardMessage.Types.Ranks.Ace) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Rank);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Suit != global::XddCards.Grpc.Games.CardMessage.Types.Suits.Clubs) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Suit);
      }
      if (Rank != global::XddCards.Grpc.Games.CardMessage.Types.Ranks.Ace) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Rank);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Suit != global::XddCards.Grpc.Games.CardMessage.Types.Suits.Clubs) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Suit);
      }
      if (Rank != global::XddCards.Grpc.Games.CardMessage.Types.Ranks.Ace) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Rank);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CardMessage other) {
      if (other == null) {
        return;
      }
      if (other.Suit != global::XddCards.Grpc.Games.CardMessage.Types.Suits.Clubs) {
        Suit = other.Suit;
      }
      if (other.Rank != global::XddCards.Grpc.Games.CardMessage.Types.Ranks.Ace) {
        Rank = other.Rank;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Suit = (global::XddCards.Grpc.Games.CardMessage.Types.Suits) input.ReadEnum();
            break;
          }
          case 16: {
            Rank = (global::XddCards.Grpc.Games.CardMessage.Types.Ranks) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Suit = (global::XddCards.Grpc.Games.CardMessage.Types.Suits) input.ReadEnum();
            break;
          }
          case 16: {
            Rank = (global::XddCards.Grpc.Games.CardMessage.Types.Ranks) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CardMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Suits {
        [pbr::OriginalName("Clubs")] Clubs = 0,
        [pbr::OriginalName("Diamonds")] Diamonds = 1,
        [pbr::OriginalName("Hearts")] Hearts = 2,
        [pbr::OriginalName("Spades")] Spades = 3,
      }

      public enum Ranks {
        [pbr::OriginalName("Ace")] Ace = 0,
        [pbr::OriginalName("Two")] Two = 1,
        [pbr::OriginalName("Three")] Three = 2,
        [pbr::OriginalName("Four")] Four = 3,
        [pbr::OriginalName("Five")] Five = 4,
        [pbr::OriginalName("Six")] Six = 5,
        [pbr::OriginalName("Seven")] Seven = 6,
        [pbr::OriginalName("Eight")] Eight = 7,
        [pbr::OriginalName("Nine")] Nine = 8,
        [pbr::OriginalName("Ten")] Ten = 9,
        [pbr::OriginalName("Jack")] Jack = 10,
        [pbr::OriginalName("Queen")] Queen = 11,
        [pbr::OriginalName("King")] King = 12,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
