// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Games/BlackJack/Player.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace XddCards.Grpc.Games.BlackJack {
  public static partial class PlayerGrpc
  {
    static readonly string __ServiceName = "BlackJack.PlayerGrpc";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XddCards.Grpc.Games.BlackJack.Player> __Marshaller_BlackJack_Player = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XddCards.Grpc.Games.BlackJack.Player.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XddCards.Grpc.Games.BlackJack.CanTurnReply> __Marshaller_BlackJack_CanTurnReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XddCards.Grpc.Games.BlackJack.CanTurnReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XddCards.Grpc.Games.BlackJack.ScoresReply> __Marshaller_BlackJack_ScoresReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XddCards.Grpc.Games.BlackJack.ScoresReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XddCards.Grpc.Games.BlackJack.StatusReply> __Marshaller_BlackJack_StatusReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XddCards.Grpc.Games.BlackJack.StatusReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XddCards.Grpc.Games.BlackJack.HitReply> __Marshaller_BlackJack_HitReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XddCards.Grpc.Games.BlackJack.HitReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XddCards.Grpc.Games.BlackJack.StandReply> __Marshaller_BlackJack_StandReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XddCards.Grpc.Games.BlackJack.StandReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.CanTurnReply> __Method_CanTurn = new grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.CanTurnReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CanTurn",
        __Marshaller_BlackJack_Player,
        __Marshaller_BlackJack_CanTurnReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.ScoresReply> __Method_GetScores = new grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.ScoresReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetScores",
        __Marshaller_BlackJack_Player,
        __Marshaller_BlackJack_ScoresReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.StatusReply> __Method_GetStatus = new grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.StatusReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetStatus",
        __Marshaller_BlackJack_Player,
        __Marshaller_BlackJack_StatusReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.HitReply> __Method_Hit = new grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.HitReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Hit",
        __Marshaller_BlackJack_Player,
        __Marshaller_BlackJack_HitReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.StandReply> __Method_Stand = new grpc::Method<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.StandReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Stand",
        __Marshaller_BlackJack_Player,
        __Marshaller_BlackJack_StandReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::XddCards.Grpc.Games.BlackJack.PlayerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PlayerGrpc</summary>
    [grpc::BindServiceMethod(typeof(PlayerGrpc), "BindService")]
    public abstract partial class PlayerGrpcBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XddCards.Grpc.Games.BlackJack.CanTurnReply> CanTurn(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XddCards.Grpc.Games.BlackJack.ScoresReply> GetScores(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XddCards.Grpc.Games.BlackJack.StatusReply> GetStatus(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XddCards.Grpc.Games.BlackJack.HitReply> Hit(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XddCards.Grpc.Games.BlackJack.StandReply> Stand(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PlayerGrpc</summary>
    public partial class PlayerGrpcClient : grpc::ClientBase<PlayerGrpcClient>
    {
      /// <summary>Creates a new client for PlayerGrpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PlayerGrpcClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PlayerGrpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PlayerGrpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PlayerGrpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PlayerGrpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.CanTurnReply CanTurn(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CanTurn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.CanTurnReply CanTurn(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CanTurn, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.CanTurnReply> CanTurnAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CanTurnAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.CanTurnReply> CanTurnAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CanTurn, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.ScoresReply GetScores(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetScores(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.ScoresReply GetScores(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetScores, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.ScoresReply> GetScoresAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetScoresAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.ScoresReply> GetScoresAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetScores, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.StatusReply GetStatus(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.StatusReply GetStatus(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStatus, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.StatusReply> GetStatusAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.StatusReply> GetStatusAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStatus, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.HitReply Hit(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Hit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.HitReply Hit(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Hit, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.HitReply> HitAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.HitReply> HitAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Hit, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.StandReply Stand(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Stand(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XddCards.Grpc.Games.BlackJack.StandReply Stand(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Stand, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.StandReply> StandAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StandAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XddCards.Grpc.Games.BlackJack.StandReply> StandAsync(global::XddCards.Grpc.Games.BlackJack.Player request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Stand, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override PlayerGrpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PlayerGrpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PlayerGrpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CanTurn, serviceImpl.CanTurn)
          .AddMethod(__Method_GetScores, serviceImpl.GetScores)
          .AddMethod(__Method_GetStatus, serviceImpl.GetStatus)
          .AddMethod(__Method_Hit, serviceImpl.Hit)
          .AddMethod(__Method_Stand, serviceImpl.Stand).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PlayerGrpcBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CanTurn, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.CanTurnReply>(serviceImpl.CanTurn));
      serviceBinder.AddMethod(__Method_GetScores, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.ScoresReply>(serviceImpl.GetScores));
      serviceBinder.AddMethod(__Method_GetStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.StatusReply>(serviceImpl.GetStatus));
      serviceBinder.AddMethod(__Method_Hit, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.HitReply>(serviceImpl.Hit));
      serviceBinder.AddMethod(__Method_Stand, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XddCards.Grpc.Games.BlackJack.Player, global::XddCards.Grpc.Games.BlackJack.StandReply>(serviceImpl.Stand));
    }

  }
}
#endregion
